baseurl: ""
repository: adaptivadesignlab/adaptivadesignlab.github.io
exclude: ['README.md']
permalink: pretty
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/:num/"
sass:
    sass_dir: ./assets/css
